#ifndef _INS_H
#define _INS_H

class INS {
  protected:
    Double accAltitude;
    Double accEast;
    Double accNorth;
    Double altitude;
    Double apolune;
    Double attUr;
    Double attFr;
    Double attLs;
    char   displayAccAltitude[16];
    char   displayAccEast[16];
    char   displayAccNorth[16];
    char   displayPosAltitude[16];
    char   displayPosEast[16];
    char   displayPosNorth[16];
    char   displayVelAltitude[16];
    char   displayVelEast[16];
    char   displayVelNorth[16];
    char   displayApolune[16];
    char   displayPerilune[16];
    char   displayMomEast[16];
    char   displayMomNorth[16];
    Double   latitude;
    Double   lastVelAltitude;
    Double   lastVelEast;
    Double   lastVelNorth;
    Double   longitude;
    Int8     mode;
    Double   momEast;
    Double   momNorth;
    Double   tMomEast;
    Double   tMomNorth;
    Double   rMomEast;
    Double   rMomNorth;
    Double   orbitTime;
    Double   perilune;
    Double   relAccAltitude;
    Double   relAccEast;
    Double   relAccNorth;
    Double   relAltitude;
    Vector   relPos;
    Vector   relVel;
    Double   relLongitude;
    Double   relLatitude;
    Double   tarLongitude;
    Double   tarLatitude;
    Vehicle* spacecraft;
    Vehicle* target;
    Int32    hasSignal();
    void     noData();
    void     populatePosAbs();
    void     populatePosTar();
    void     populatePosRel();
    void     populateOrbAbs();
    void     populateOrbTar();
    void     populateOrbRel();
    void     printVelocity(Double v,char* buffer);
  public:
    INS();
    ~INS();
    void     Cycle();
    Double   Altitude();
    Double   Apolune();
    Double   AttUr();
    Double   AttFr();
    Double   AttLs();
    char*    DisplayAccAltitude();
    char*    DisplayAccEast();
    char*    DisplayAccNorth();
    char*    DisplayPosAltitude();
    char*    DisplayPosEast();
    char*    DisplayPosNorth();
    char*    DisplayVelAltitude();
    char*    DisplayVelEast();
    char*    DisplayVelNorth();
    char*    DisplayApolune();
    char*    DisplayPerilune();
    char*    DisplayMomEast();
    char*    DisplayMomNorth();
    Int8     Mode();
    Int8     Mode(Int8 i);
    Double   Latitude();
    Double   Longitude();
    Double   MomEast();
    Double   MomNorth();
    Double   Perilune();
    Double   RelAltitude();
    Vector   RelPos();
    Vector   RelVel();
    void     Reset();
    Double   RelLongitude();
    Double   RelLatitude();
    Double   TargetLongitude();
    Double   TargetLatitude();
    Double   TargetMomEast();
    Double   TargetMomNorth();
    Double   RelMomEast();
    Double   RelMomNorth();
    Vehicle* Spacecraft();
    Vehicle* Spacecraft(Vehicle* v);
    Vehicle* Target();
    Vehicle* Target(Vehicle* v);
  };

#endif

